name: Node.js CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo under GH workspace
      uses: actions/checkout@v3

    - name: Use nodejs
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: npm

    - name: Install deps without updating package-lock.json
      run: npm i --no-save

    - name: Run the CI build
      run: npm run ci
